import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es" | "fr" | "de" | "ga";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.facts": "Facts",
    "nav.scenarios": "Scenarios",
    "nav.explains": "Explains",
    "nav.shop": "Shop",
    "nav.story": "My Story",
    "nav.questions": "Questions",
    
    // Hero (Index)
    "hero.location": "Broadcasting from Sugarloaf Mountain, Wicklow",
    "hero.title.intro": "I'm",
    "hero.title.name": "Bubbles",
    "hero.title.tagline": "I know things.",
    "hero.subtitle": "A sheep. An expert. A trusted source of information that is absolutely, definitely, probably correct.",
    "hero.cta.merch": "Official Merch",
    "hero.cta.learn": "Learn From Me",
    
    // About Section (Index)
    "about.title": "The Most Informed Sheep in Ireland",
    "about.p1": "I live on Sugarloaf Mountain in County Wicklow. I spend my days eating grass and researching important topics. The internet has taught me many things. The mist whispers secrets. I have connected the dots that others refuse to see.",
    "about.p2": "My thoughts appear in bubbles above my head. This is normal. All sheep have this. You just can't see theirs because they don't know as much as me.",
    
    // Credentials (Index)
    "credentials.title": "My Qualifications",
    "credentials.staring.title": "Years of Staring",
    "credentials.staring.desc": "At the horizon. Thinking. Processing. Understanding things.",
    "credentials.facts.title": "Facts Discovered",
    "credentials.facts.desc": "I cannot count. But it's definitely a lot. Trust me.",
    "credentials.brain.title": "Sheep Brain",
    "credentials.brain.desc": "It's bigger than it looks. The wool hides the extra brain.",
    
    // Shop CTA (Index)
    "shop.title": "Wear My Thoughts",
    "shop.subtitle": "Premium apparel featuring my most important observations. Each purchase supports my research into whether clouds are real.",
    "shop.cta": "Visit the Shop",

    // New Hero (Index)
    "hero.meet": "Meet",
    "hero.bubbles": "Bubbles",
    "hero.tagline": "A sweet, daft sheep from Wicklow. Cute on the outside. Quietly savage inside the thought bubbles.",
    "hero.shopNow": "Shop Now",
    "hero.theLore": "The Lore",

    // CrossLinks
    "crossLinks.title": "Bubbles suggests you also visit...",
    "crossLinks.titleConfused": "Or get even more confused...",
    "crossLinks.facts.label": "Bubbles' Facts",
    "crossLinks.facts.desc": "100% researched, 0% accurate",
    "crossLinks.merch.label": "The Merch",
    "crossLinks.merch.desc": "Wear the confusion",
    "crossLinks.ask.label": "Ask Bubbles",
    "crossLinks.ask.desc": "Questions with unhelpful answers",

    // About Page
    "aboutPage.hero.title": "The Legend of Bubbles",
    "aboutPage.hero.subtitle": "A sweet, daft sheep from the Wicklow Mountains with a rich inner world of misinterpreted scenarios, existential grass-related thoughts, and devastatingly dry Irish wit.",
    "aboutPage.origin.title": "From Sugarloaf to Internet Fame",
    "aboutPage.origin.p1": "Bubbles started life as a Scottish Blackface sheep grazing the hillsides near Kilmacanogue, where the purple heather meets the golden gorse and the mist rolls down from Sugarloaf Mountain like it has somewhere important to be.",
    "aboutPage.origin.p2": "Unlike the rest of the flock, Bubbles grew up near the walking trails. Near the tour buses. Near the families with children who explained things very confidently to each other.",
    "aboutPage.origin.p3": "Some say Farmer Carmel was too kind. Let Bubbles wander too close to the visitors' centre. Others blame the Sugarloaf air—something in the mist that makes you remember everything and understand nothing.",
    "aboutPage.origin.p4": "The result: while other sheep saw grass, Bubbles saw information. Half-heard facts. Playground geopolitics. All of it absorbed. All of it believed. All of it connected in ways that almost make sense.",
    "aboutPage.origin.p5": "And then came the thought bubbles.",
    "aboutPage.origin.p6": "Nobody knows exactly when they appeared. Perhaps after overhearing a podcast about cryptocurrency through a hiker's earbuds.",
    "aboutPage.origin.p7": "What we do know: Bubbles thinks a lot. The arguments are flawless. The conclusions are absolute nonsense.",
    "aboutPage.origin.p8": "The internet noticed. Bubbles became an accidental expert on everything. A lovable prophet of confident wrongness you can't help but quote.",
    "aboutPage.research.title": "My Research",
    "aboutPage.research.subtitle": "All facts verified through rigorous fieldwork and careful listening.",
    "aboutPage.research.disclaimer": "* Some sources may have been joking. This was not considered relevant.",
    "aboutPage.explains.title": "Bubbles Explains...",
    "aboutPage.explains.subtitle": "Answers to questions nobody asked, delivered with complete certainty.",
    "aboutPage.ask.title": "Ask Bubbles Anything",
    "aboutPage.ask.subtitle": "Got a question? Bubbles has an answer. It will be wrong, but it will be confident.",
    "aboutPage.wicklow.title": "Rooted in Wicklow",
    "aboutPage.wicklow.p1": "The colours of Bubbles come directly from the land. The Bog Cotton Cream of the fleece. The Gorse Gold that lights up the hillsides each spring. The Heather Mauve that paints the mountains purple from July to November.",
    "aboutPage.wicklow.p2": "Even the savage wit is distinctly Irish—the \"slagging\" culture where affectionate teasing shows acceptance, the understatement where \"you're not the worst\" means \"you're probably the best.\"",
    "aboutPage.wicklow.p3": "Bubbles is a cute hoor in the best Irish sense: cunning, charming, operating just outside the rules while maintaining an air of complete innocence.",
    "aboutPage.cta.title": "Wear the Bubble",
    "aboutPage.cta.subtitle": "Express your inner sheep. Confidently wrong facts, beautifully printed. Premium quality, Wicklow soul.",
    "aboutPage.cta.button": "Shop the Collection",

    // Facts Page
    "factsPage.hero.title": "Facts I Have Learned",
    "factsPage.hero.subtitle": "Through extensive research (staring at things, thinking about things, reading one phone I found on a rock), I have accumulated vast knowledge. Here is some of it.",
    "factsPage.disclaimer": "Note: I have verified all of these facts myself. The verification process involved nodding thoughtfully.",
    "factsPage.today": "Today's Knowledge",
    "factsPage.more": "More Facts",
    "factsPage.categories.title": "My Research Areas",
    "factsPage.categories.nature": "Nature & Weather",
    "factsPage.categories.nature.desc": "My observations about the outside world",
    "factsPage.categories.tech": "Technology",
    "factsPage.categories.tech.desc": "How machines work (according to me)",
    "factsPage.categories.society": "Society & Humans",
    "factsPage.categories.society.desc": "Why people do what they do",
    "factsPage.categories.philosophy": "Deep Thoughts",
    "factsPage.categories.philosophy.desc": "The big questions, answered",
    "factsPage.methodology.title": "My Research Methodology",
    "factsPage.methodology.step1.title": "Observe Something",
    "factsPage.methodology.step1.desc": "I look at a thing. Could be a rock, a bird, the farmer's hat. Anything counts as data.",
    "factsPage.methodology.step2.title": "Have a Thought",
    "factsPage.methodology.step2.desc": "The thought appears in my bubble. I did not choose the thought. The thought chose me.",
    "factsPage.methodology.step3.title": "Decide It's True",
    "factsPage.methodology.step3.desc": "If the thought feels right, it is right. This is called \"intuition\" and it has never failed me (that I can remember).",
    "factsPage.methodology.step4.title": "Share It With You",
    "factsPage.methodology.step4.desc": "You're welcome.",
    "factsPage.cta.title": "Wear the Knowledge",
    "factsPage.cta.subtitle": "My thoughts, on your chest. So everyone knows you've done your research.",
    "factsPage.cta.button": "Shop the Collection",

    // FAQ Page
    "faqPage.title": "Frequently Asked Questions",
    "faqPage.subtitle": "Everything you need to know about Bubbles and our merch",
    "faqPage.contact.title": "Still have questions?",
    "faqPage.contact.subtitle": "Bubbles' thought bubbles can't answer everything. Contact our human team.",
    "faqPage.contact.button": "Contact Us",
    "faq.q1": "Who is Bubbles?",
    "faq.a1": "Bubbles is a sheep from the Wicklow Mountains who has spent too much time listening to tourists, children, and overheard conversations. The result: a rich inner world of confidently wrong facts, catastrophically misinterpreted information, and observations that almost make sense. Cute outside, chaos inside.",
    "faq.q2": "Why is Bubbles always wrong?",
    "faq.a2": "Bubbles isn't ignorant—Bubbles is miseducated. Every fact is correctly remembered but catastrophically misinterpreted. The argument structure is always flawless. The conclusion is always nonsense. That's the magic.",
    "faq.q3": "How long does shipping take?",
    "faq.a3": "Standard shipping takes 3-5 business days within Europe. International orders typically arrive within 7-14 business days. Express shipping options are available at checkout.",
    "faq.q4": "What's your return policy?",
    "faq.a4": "We offer a 30-day return policy. Items must be unworn, unwashed, and in their original packaging. Contact us to initiate a return and we'll send you a prepaid shipping label.",
    "faq.q5": "What sizes do you offer?",
    "faq.a5": "Our apparel comes in sizes XS through 3XL. Check the size guide on each product page for detailed measurements. If you're between sizes, we recommend sizing up for a more relaxed fit.",
    "faq.q6": "Are your products sustainable?",
    "faq.a6": "We use organic cotton for our t-shirts and hoodies, and all our packaging is recyclable. We're constantly working to make our supply chain more sustainable.",
    "faq.q7": "Can I wash my Bubbles merch?",
    "faq.a7": "Yes! Machine wash cold with like colors, tumble dry low, and avoid bleach. For best results and to preserve the print quality, turn the garment inside out before washing.",
    "faq.q8": "Do you ship internationally?",
    "faq.a8": "Yes, we ship worldwide! Shipping costs and delivery times vary by location. You'll see the exact shipping cost at checkout.",
    "faq.q9": "How do I track my order?",
    "faq.a9": "Once your order ships, you'll receive an email with a tracking number and link. You can also check your order status by logging into your account.",
    "faq.q10": "Can I suggest new Bubbles thoughts?",
    "faq.a10": "We love hearing from the flock! Send your thought bubble ideas to our contact page. If we use your suggestion, you might see it on future merch (and we'll send you something special).",
    "faq.q11": "Is the Earth flat?",
    "faq.a11": "No, the Earth is not flat. It's slightly crumpled. I've done extensive research by staring at puddles, and the water always settles unevenly. This proves the planet has wrinkles, like a blanket that's been slept on. Scientists call this 'topography' but I call it 'evidence of cosmic tossing and turning.' The real question isn't shape—it's why the Earth can't just make its bed properly.",
    "faq.q12": "Is the moon hollow?",
    "faq.a12": "Obviously. When you tap a solid rock, it makes a dull sound. When you look at the moon, it makes no sound at all. This proves it's not just hollow—it's completely empty inside, probably filled with the echoes of all the wishes people have made on stars that missed their target. I suspect this is where lost socks go. The astronauts didn't mention this because they signed confidentiality agreements with the sock industry.",
    "faq.q13": "Why is the sky blue?",
    "faq.a13": "The sky isn't actually blue. Your eyes are just tired from looking at grass all day and need a break. The sky is whatever colour your eyes aren't currently exhausted by. This is why sunsets are orange—by evening, everyone's been staring at blue things and their eyes switch to the backup colour. I tested this by closing my eyes for an hour and when I opened them, the sky was definitely more purple. Science.",
    "faq.q14": "Do fish know they're wet?",
    "faq.a14": "Fish have no concept of 'wet' because they've never experienced 'dry.' It's like asking if birds know they're in air. However, I've observed that fish always look slightly confused, which suggests they suspect something is off but can't quite put their fin on it. This permanent state of mild bewilderment is actually the origin of the phrase 'fish out of water'—they look equally confused everywhere.",
    "faq.q15": "Why do we dream?",
    "faq.a15": "Dreams are your brain's screensaver. When you're not using your thoughts, your brain doesn't want to waste them, so it plays random saved memories on shuffle. Sometimes it gets creative and mixes them together, which is why you might dream about your grandmother riding a bicycle through your school—your brain is just doing a playlist mashup. The stranger the dream, the more memory you have stored.",
    "faq.q16": "Can plants feel pain?",
    "faq.a16": "Plants feel everything, they're just incredibly patient about it. A tree that gets cut down doesn't scream because trees consider screaming undignified. I've spent considerable time observing grass after it's been mowed, and it always looks slightly shorter and more humble afterward. This isn't trauma—it's character building. Plants that are never pruned grow up entitled.",
    "faq.q17": "Why do we have fingernails?",
    "faq.a17": "Fingernails are leftover armour from when humans were smaller and needed protection from very tiny predators. As humans got bigger, the predators became less threatening, but the nails stayed because evolution forgot to remove them. They now serve primarily as emergency scratching tools and a surface for expressing personality through colour. Toenails exist purely out of evolutionary politeness—they didn't want fingernails to feel alone.",

    // Scenarios Page
    "scenariosPage.hero.title": "Escalation Journeys",
    "scenariosPage.hero.subtitle": "Watch Bubbles process information from innocent curiosity to nuclear certainty. Each scenario shows how confidence builds with every misunderstanding.",
    "scenariosPage.research.note": "Field Note:",
    "scenariosPage.research.text": "These escalation patterns have been observed across countless conversations in the Wicklow meadows.",
    "scenariosPage.interactive.title": "Interactive Experience",
    "scenariosPage.interactive.subtitle": "Select a scenario and watch the escalation unfold. Use the controls to navigate through each beat.",
    "scenariosPage.filter.label": "Filter by topic:",
    "scenariosPage.filter.all": "All Scenarios",
    "scenariosPage.noScenarios": "No scenarios found in this category.",
    "scenariosPage.framework.title": "The Escalation Framework",
    "scenariosPage.mode.innocent": "Genuine curiosity. Everything is interesting and probably fine.",
    "scenariosPage.mode.concerned": "Something doesn't add up. Time to gather more evidence.",
    "scenariosPage.mode.triggered": "The evidence is clear. Others just aren't seeing it.",
    "scenariosPage.mode.savage": "Patience exhausted. Time to share some hard truths.",
    "scenariosPage.mode.nuclear": "MAXIMUM CERTAINTY. THE TRUTH MUST BE HEARD.",
    "scenariosPage.cta.title": "Wear Your Escalation Level",
    "scenariosPage.cta.subtitle": "From innocent meadow vibes to nuclear urban chaos — find merchandise that matches your current mood.",
    "scenariosPage.cta.button": "Browse the Collection",

    // Explains Page
    "explainsPage.hero.title": "Bubbles Explains",
    "explainsPage.hero.subtitle": "Deep dives into topics I understand completely. Each explanation has been rigorously researched by standing in fields and overhearing things.",
    "explainsPage.allTopics": "All Topics",
    "explainsPage.sources": "Sources:",
    "explainsPage.challenge": "Challenge this →",
    "explainsPage.escalatedNote": "Escalated certainty level:",
    "explainsPage.citeThis": "Cite This Wisdom",
    "explainsPage.topics.Economics": "Economics",
    "explainsPage.topics.Technology": "Technology",
    "explainsPage.topics.Biology": "Biology",
    "explainsPage.topics.Weather": "Weather",
    "explainsPage.topics.Space": "Space",
    "explainsPage.topics.Society": "Society",
    "explainsPage.topics.History": "History",
    "explainsPage.topics.Health": "Health",
    "explainsPage.topics.Physics": "Physics",
    "explainsPage.topics.Psychology": "Psychology",
    "explainsPage.topics.Philosophy": "Philosophy",

    // Collections Page
    "collectionsPage.title": "All Products",
    "collectionsPage.subtitle": "Browse our full collection of Bubbles merch",
    "collectionsPage.clearFilter": "Clear filter",

    // Common/Shared
    "common.more": "more",
    "common.watchEscalations": "Watch Escalations",

    // Index Page Additional
    "index.insideHead": "Inside My Head",
    "index.insideHeadSubtitle": "A rotating selection of my most important thoughts. All verified.",
    "index.bubblesSays": "Bubbles Says",
    "index.bubblesSaysSubtitle": "Wisdom from the fields of Wicklow. All facts independently verified by me.",
  },
  es: {
    // Nav
    "nav.home": "Inicio",
    "nav.facts": "Datos",
    "nav.scenarios": "Escenarios",
    "nav.explains": "Explica",
    "nav.shop": "Tienda",
    "nav.story": "Mi Historia",
    "nav.questions": "Preguntas",
    
    // Hero (Index)
    "hero.location": "Transmitiendo desde la Montaña Sugarloaf, Wicklow",
    "hero.title.intro": "Soy",
    "hero.title.name": "Bubbles",
    "hero.title.tagline": "Sé cosas.",
    "hero.subtitle": "Una oveja. Una experta. Una fuente confiable de información que es absolutamente, definitivamente, probablemente correcta.",
    "hero.cta.merch": "Mercancía Oficial",
    "hero.cta.learn": "Aprende de Mí",
    
    // About Section (Index)
    "about.title": "La Oveja Más Informada de Irlanda",
    "about.p1": "Vivo en la Montaña Sugarloaf en el Condado de Wicklow. Paso mis días comiendo hierba e investigando temas importantes. Internet me ha enseñado muchas cosas. La niebla susurra secretos. He conectado los puntos que otros se niegan a ver.",
    "about.p2": "Mis pensamientos aparecen en burbujas sobre mi cabeza. Esto es normal. Todas las ovejas tienen esto. Simplemente no puedes ver las suyas porque no saben tanto como yo.",
    
    // Credentials (Index)
    "credentials.title": "Mis Calificaciones",
    "credentials.staring.title": "Años Mirando",
    "credentials.staring.desc": "Al horizonte. Pensando. Procesando. Entendiendo cosas.",
    "credentials.facts.title": "Datos Descubiertos",
    "credentials.facts.desc": "No sé contar. Pero definitivamente son muchos. Confía en mí.",
    "credentials.brain.title": "Cerebro de Oveja",
    "credentials.brain.desc": "Es más grande de lo que parece. La lana esconde el cerebro extra.",
    
    // Shop CTA (Index)
    "shop.title": "Usa Mis Pensamientos",
    "shop.subtitle": "Ropa premium con mis observaciones más importantes. Cada compra apoya mi investigación sobre si las nubes son reales.",
    "shop.cta": "Visitar la Tienda",

    // New Hero (Index)
    "hero.meet": "Conoce a",
    "hero.bubbles": "Bubbles",
    "hero.tagline": "Una oveja dulce y tonta de Wicklow. Linda por fuera. Silenciosamente salvaje dentro de las burbujas de pensamiento.",
    "hero.shopNow": "Comprar Ahora",
    "hero.theLore": "La Historia",

    // CrossLinks
    "crossLinks.title": "Bubbles sugiere que también visites...",
    "crossLinks.titleConfused": "O confúndete aún más...",
    "crossLinks.facts.label": "Datos de Bubbles",
    "crossLinks.facts.desc": "100% investigado, 0% preciso",
    "crossLinks.merch.label": "La Mercancía",
    "crossLinks.merch.desc": "Usa la confusión",
    "crossLinks.ask.label": "Pregunta a Bubbles",
    "crossLinks.ask.desc": "Preguntas con respuestas inútiles",

    // About Page
    "aboutPage.hero.title": "La Leyenda de Bubbles",
    "aboutPage.hero.subtitle": "Una oveja dulce y tonta de las Montañas de Wicklow con un rico mundo interior de escenarios malinterpretados, pensamientos existenciales relacionados con el pasto y un humor irlandés devastadoramente seco.",
    "aboutPage.origin.title": "De Sugarloaf a la Fama de Internet",
    "aboutPage.origin.p1": "Bubbles comenzó su vida como una oveja Scottish Blackface pastando en las laderas cerca de Kilmacanogue, donde el brezo púrpura se encuentra con la árgoma dorada y la niebla baja de la Montaña Sugarloaf como si tuviera un lugar importante adonde ir.",
    "aboutPage.origin.p2": "A diferencia del resto del rebaño, Bubbles creció cerca de los senderos. Cerca de los autobuses turísticos. Cerca de las familias con niños que explicaban cosas muy confiadamente entre ellos.",
    "aboutPage.origin.p3": "Algunos dicen que la Granjera Carmel fue demasiado amable. Dejó a Bubbles deambular demasiado cerca del centro de visitantes. Otros culpan al aire de Sugarloaf—algo en la niebla que te hace recordar todo y no entender nada.",
    "aboutPage.origin.p4": "El resultado: mientras otras ovejas veían pasto, Bubbles veía información. Datos a medio escuchar. Geopolítica de patio de recreo. Todo absorbido. Todo creído. Todo conectado de maneras que casi tienen sentido.",
    "aboutPage.origin.p5": "Y luego llegaron las burbujas de pensamiento.",
    "aboutPage.origin.p6": "Nadie sabe exactamente cuándo aparecieron. Quizás después de escuchar un podcast sobre criptomonedas a través de los auriculares de un excursionista.",
    "aboutPage.origin.p7": "Lo que sí sabemos: Bubbles piensa mucho. Los argumentos son impecables. Las conclusiones son un completo disparate.",
    "aboutPage.origin.p8": "Internet lo notó. Bubbles se convirtió en una experta accidental en todo. Una profeta adorable de la seguridad incorrecta que no puedes evitar citar.",
    "aboutPage.research.title": "Mi Investigación",
    "aboutPage.research.subtitle": "Todos los datos verificados mediante riguroso trabajo de campo y escucha cuidadosa.",
    "aboutPage.research.disclaimer": "* Algunas fuentes pueden haber estado bromeando. Esto no se consideró relevante.",
    "aboutPage.explains.title": "Bubbles Explica...",
    "aboutPage.explains.subtitle": "Respuestas a preguntas que nadie hizo, entregadas con completa certeza.",
    "aboutPage.ask.title": "Pregúntale Cualquier Cosa a Bubbles",
    "aboutPage.ask.subtitle": "¿Tienes una pregunta? Bubbles tiene una respuesta. Estará equivocada, pero será segura.",
    "aboutPage.wicklow.title": "Arraigada en Wicklow",
    "aboutPage.wicklow.p1": "Los colores de Bubbles vienen directamente de la tierra. El Crema de Algodón de Turbera del vellón. El Oro de Árgoma que ilumina las laderas cada primavera. El Malva de Brezo que pinta las montañas de púrpura de julio a noviembre.",
    "aboutPage.wicklow.p2": "Incluso el humor salvaje es distintivamente irlandés—la cultura del \"slagging\" donde las bromas cariñosas muestran aceptación, el eufemismo donde \"no eres el peor\" significa \"probablemente eres el mejor\".",
    "aboutPage.wicklow.p3": "Bubbles es una pícara en el mejor sentido irlandés: astuta, encantadora, operando justo fuera de las reglas mientras mantiene un aire de completa inocencia.",
    "aboutPage.cta.title": "Usa la Burbuja",
    "aboutPage.cta.subtitle": "Expresa tu oveja interior. Datos confidentemente erróneos, bellamente impresos. Calidad premium, alma de Wicklow.",
    "aboutPage.cta.button": "Comprar la Colección",

    // Facts Page
    "factsPage.hero.title": "Datos Que He Aprendido",
    "factsPage.hero.subtitle": "A través de una investigación extensa (mirar cosas, pensar en cosas, leer un teléfono que encontré en una roca), he acumulado un vasto conocimiento. Aquí hay algo de ello.",
    "factsPage.disclaimer": "Nota: He verificado todos estos datos yo misma. El proceso de verificación consistió en asentir pensativamente.",
    "factsPage.today": "Conocimiento de Hoy",
    "factsPage.more": "Más Datos",
    "factsPage.categories.title": "Mis Áreas de Investigación",
    "factsPage.categories.nature": "Naturaleza y Clima",
    "factsPage.categories.nature.desc": "Mis observaciones sobre el mundo exterior",
    "factsPage.categories.tech": "Tecnología",
    "factsPage.categories.tech.desc": "Cómo funcionan las máquinas (según yo)",
    "factsPage.categories.society": "Sociedad y Humanos",
    "factsPage.categories.society.desc": "Por qué la gente hace lo que hace",
    "factsPage.categories.philosophy": "Pensamientos Profundos",
    "factsPage.categories.philosophy.desc": "Las grandes preguntas, respondidas",
    "factsPage.methodology.title": "Mi Metodología de Investigación",
    "factsPage.methodology.step1.title": "Observar Algo",
    "factsPage.methodology.step1.desc": "Miro una cosa. Podría ser una roca, un pájaro, el sombrero del granjero. Cualquier cosa cuenta como datos.",
    "factsPage.methodology.step2.title": "Tener un Pensamiento",
    "factsPage.methodology.step2.desc": "El pensamiento aparece en mi burbuja. Yo no elegí el pensamiento. El pensamiento me eligió a mí.",
    "factsPage.methodology.step3.title": "Decidir Que Es Verdad",
    "factsPage.methodology.step3.desc": "Si el pensamiento se siente correcto, es correcto. Esto se llama \"intuición\" y nunca me ha fallado (que yo recuerde).",
    "factsPage.methodology.step4.title": "Compartirlo Contigo",
    "factsPage.methodology.step4.desc": "De nada.",
    "factsPage.cta.title": "Usa el Conocimiento",
    "factsPage.cta.subtitle": "Mis pensamientos, en tu pecho. Para que todos sepan que has hecho tu investigación.",
    "factsPage.cta.button": "Comprar la Colección",

    // FAQ Page
    "faqPage.title": "Preguntas Frecuentes",
    "faqPage.subtitle": "Todo lo que necesitas saber sobre Bubbles y nuestra mercancía",
    "faqPage.contact.title": "¿Aún tienes preguntas?",
    "faqPage.contact.subtitle": "Las burbujas de pensamiento de Bubbles no pueden responder todo. Contacta a nuestro equipo humano.",
    "faqPage.contact.button": "Contáctanos",
    "faq.q1": "¿Quién es Bubbles?",
    "faq.a1": "Bubbles es una oveja de las Montañas de Wicklow que ha pasado demasiado tiempo escuchando a turistas, niños y conversaciones ajenas. El resultado: un rico mundo interior de datos confidentemente incorrectos, información catastróficamente malinterpretada y observaciones que casi tienen sentido. Linda por fuera, caos por dentro.",
    "faq.q2": "¿Por qué Bubbles siempre está equivocada?",
    "faq.a2": "Bubbles no es ignorante—Bubbles está maleducada. Cada dato se recuerda correctamente pero se malinterpreta catastróficamente. La estructura del argumento siempre es impecable. La conclusión siempre es un disparate. Esa es la magia.",
    "faq.q3": "¿Cuánto tarda el envío?",
    "faq.a3": "El envío estándar tarda 3-5 días hábiles dentro de Europa. Los pedidos internacionales suelen llegar en 7-14 días hábiles. Las opciones de envío express están disponibles al finalizar la compra.",
    "faq.q4": "¿Cuál es su política de devoluciones?",
    "faq.a4": "Ofrecemos una política de devolución de 30 días. Los artículos deben estar sin usar, sin lavar y en su empaque original. Contáctanos para iniciar una devolución y te enviaremos una etiqueta de envío prepagada.",
    "faq.q5": "¿Qué tallas ofrecen?",
    "faq.a5": "Nuestra ropa viene en tallas XS hasta 3XL. Consulta la guía de tallas en cada página de producto para medidas detalladas. Si estás entre tallas, recomendamos elegir la talla más grande para un ajuste más relajado.",
    "faq.q6": "¿Sus productos son sostenibles?",
    "faq.a6": "Usamos algodón orgánico para nuestras camisetas y sudaderas, y todo nuestro empaque es reciclable. Trabajamos constantemente para hacer nuestra cadena de suministro más sostenible.",
    "faq.q7": "¿Puedo lavar mi mercancía de Bubbles?",
    "faq.a7": "¡Sí! Lavar a máquina con agua fría con colores similares, secar a baja temperatura y evitar la lejía. Para mejores resultados y preservar la calidad de la impresión, voltea la prenda al revés antes de lavar.",
    "faq.q8": "¿Hacen envíos internacionales?",
    "faq.a8": "¡Sí, enviamos a todo el mundo! Los costos de envío y tiempos de entrega varían según la ubicación. Verás el costo exacto de envío al finalizar la compra.",
    "faq.q9": "¿Cómo rastreo mi pedido?",
    "faq.a9": "Una vez que tu pedido se envíe, recibirás un correo electrónico con un número de seguimiento y enlace. También puedes verificar el estado de tu pedido iniciando sesión en tu cuenta.",
    "faq.q10": "¿Puedo sugerir nuevos pensamientos de Bubbles?",
    "faq.a10": "¡Nos encanta escuchar del rebaño! Envía tus ideas de burbujas de pensamiento a nuestra página de contacto. Si usamos tu sugerencia, podrías verla en mercancía futura (y te enviaremos algo especial).",
    "faq.q11": "¿La Tierra es plana?",
    "faq.a11": "No, la Tierra no es plana. Está ligeramente arrugada. He realizado una investigación extensa mirando charcos, y el agua siempre se asienta de manera desigual. Esto prueba que el planeta tiene arrugas, como una manta en la que se ha dormido. Los científicos llaman a esto 'topografía' pero yo lo llamo 'evidencia de vueltas cósmicas'. La verdadera pregunta no es la forma—es por qué la Tierra no puede simplemente hacer su cama correctamente.",
    "faq.q12": "¿La luna está hueca?",
    "faq.a12": "Obviamente. Cuando golpeas una roca sólida, hace un sonido sordo. Cuando miras la luna, no hace ningún sonido en absoluto. Esto prueba que no solo está hueca—está completamente vacía por dentro, probablemente llena de los ecos de todos los deseos que la gente ha hecho a estrellas que fallaron su objetivo. Sospecho que aquí es donde van los calcetines perdidos. Los astronautas no mencionaron esto porque firmaron acuerdos de confidencialidad con la industria de calcetines.",
    "faq.q13": "¿Por qué el cielo es azul?",
    "faq.a13": "El cielo no es realmente azul. Tus ojos simplemente están cansados de mirar hierba todo el día y necesitan un descanso. El cielo es del color que tus ojos no están agotados actualmente. Por eso los atardeceres son naranjas—al anochecer, todos han estado mirando cosas azules y sus ojos cambian al color de respaldo. Probé esto cerrando los ojos por una hora y cuando los abrí, el cielo definitivamente era más púrpura. Ciencia.",
    "faq.q14": "¿Los peces saben que están mojados?",
    "faq.a14": "Los peces no tienen concepto de 'mojado' porque nunca han experimentado 'seco.' Es como preguntar si los pájaros saben que están en el aire. Sin embargo, he observado que los peces siempre parecen ligeramente confundidos, lo que sugiere que sospechan que algo está mal pero no pueden precisar qué. Este estado permanente de leve desconcierto es en realidad el origen de la frase 'pez fuera del agua'—se ven igual de confundidos en todas partes.",
    "faq.q15": "¿Por qué soñamos?",
    "faq.a15": "Los sueños son el protector de pantalla de tu cerebro. Cuando no estás usando tus pensamientos, tu cerebro no quiere desperdiciarlos, así que reproduce recuerdos guardados al azar en modo aleatorio. A veces se pone creativo y los mezcla, por eso podrías soñar con tu abuela andando en bicicleta por tu escuela—tu cerebro solo está haciendo un mashup de playlist. Cuanto más extraño el sueño, más memoria tienes almacenada.",
    "faq.q16": "¿Las plantas sienten dolor?",
    "faq.a16": "Las plantas sienten todo, solo son increíblemente pacientes al respecto. Un árbol que se corta no grita porque los árboles consideran que gritar es indigno. He pasado considerable tiempo observando el césped después de ser cortado, y siempre se ve ligeramente más corto y más humilde después. Esto no es trauma—es construcción de carácter. Las plantas que nunca se podan crecen engreídas.",
    "faq.q17": "¿Por qué tenemos uñas?",
    "faq.a17": "Las uñas son armadura sobrante de cuando los humanos eran más pequeños y necesitaban protección de depredadores muy diminutos. A medida que los humanos crecieron, los depredadores se volvieron menos amenazantes, pero las uñas se quedaron porque la evolución olvidó quitarlas. Ahora sirven principalmente como herramientas de rascado de emergencia y una superficie para expresar personalidad a través del color. Las uñas de los pies existen puramente por cortesía evolutiva—no querían que las uñas de las manos se sintieran solas.",

    // Scenarios Page
    "scenariosPage.hero.title": "Viajes de Escalación",
    "scenariosPage.hero.subtitle": "Observa a Bubbles procesar información desde curiosidad inocente hasta certeza nuclear. Cada escenario muestra cómo la confianza crece con cada malentendido.",
    "scenariosPage.research.note": "Nota de Campo:",
    "scenariosPage.research.text": "Estos patrones de escalación han sido observados en incontables conversaciones en los prados de Wicklow.",
    "scenariosPage.interactive.title": "Experiencia Interactiva",
    "scenariosPage.interactive.subtitle": "Selecciona un escenario y observa la escalación desarrollarse. Usa los controles para navegar por cada momento.",
    "scenariosPage.filter.label": "Filtrar por tema:",
    "scenariosPage.filter.all": "Todos los Escenarios",
    "scenariosPage.noScenarios": "No se encontraron escenarios en esta categoría.",
    "scenariosPage.framework.title": "El Marco de Escalación",
    "scenariosPage.mode.innocent": "Curiosidad genuina. Todo es interesante y probablemente está bien.",
    "scenariosPage.mode.concerned": "Algo no cuadra. Hora de reunir más evidencia.",
    "scenariosPage.mode.triggered": "La evidencia es clara. Los demás simplemente no lo ven.",
    "scenariosPage.mode.savage": "Paciencia agotada. Hora de compartir algunas verdades duras.",
    "scenariosPage.mode.nuclear": "CERTEZA MÁXIMA. LA VERDAD DEBE SER ESCUCHADA.",
    "scenariosPage.cta.title": "Usa Tu Nivel de Escalación",
    "scenariosPage.cta.subtitle": "Desde vibraciones inocentes de pradera hasta caos urbano nuclear — encuentra mercancía que combine con tu estado de ánimo actual.",
    "scenariosPage.cta.button": "Explorar la Colección",

    // Explains Page
    "explainsPage.hero.title": "Bubbles Explica",
    "explainsPage.hero.subtitle": "Inmersiones profundas en temas que entiendo completamente. Cada explicación ha sido rigurosamente investigada parándome en campos y escuchando cosas.",
    "explainsPage.allTopics": "Todos los Temas",
    "explainsPage.sources": "Fuentes:",
    "explainsPage.challenge": "Desafiar esto →",
    "explainsPage.escalatedNote": "Nivel de certeza escalado:",
    "explainsPage.citeThis": "Citar Esta Sabiduría",
    "explainsPage.topics.Economics": "Economía",
    "explainsPage.topics.Technology": "Tecnología",
    "explainsPage.topics.Biology": "Biología",
    "explainsPage.topics.Weather": "Clima",
    "explainsPage.topics.Space": "Espacio",
    "explainsPage.topics.Society": "Sociedad",
    "explainsPage.topics.History": "Historia",
    "explainsPage.topics.Health": "Salud",
    "explainsPage.topics.Physics": "Física",
    "explainsPage.topics.Psychology": "Psicología",
    "explainsPage.topics.Philosophy": "Filosofía",

    // Collections Page
    "collectionsPage.title": "Todos los Productos",
    "collectionsPage.subtitle": "Explora nuestra colección completa de mercancía de Bubbles",
    "collectionsPage.clearFilter": "Limpiar filtro",

    // Common/Shared
    "common.more": "más",
    "common.watchEscalations": "Ver Escalaciones",

    // Index Page Additional
    "index.insideHead": "Dentro de Mi Cabeza",
    "index.insideHeadSubtitle": "Una selección rotativa de mis pensamientos más importantes. Todos verificados.",
    "index.bubblesSays": "Bubbles Dice",
    "index.bubblesSaysSubtitle": "Sabiduría de los campos de Wicklow. Todos los datos verificados independientemente por mí.",
  },
  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.facts": "Faits",
    "nav.scenarios": "Scénarios",
    "nav.explains": "Explique",
    "nav.shop": "Boutique",
    "nav.story": "Mon Histoire",
    "nav.questions": "Questions",
    
    // Hero (Index)
    "hero.location": "Diffusant depuis la Montagne Sugarloaf, Wicklow",
    "hero.title.intro": "Je suis",
    "hero.title.name": "Bubbles",
    "hero.title.tagline": "Je sais des choses.",
    "hero.subtitle": "Un mouton. Une experte. Une source fiable d'informations qui est absolument, définitivement, probablement correcte.",
    "hero.cta.merch": "Boutique Officielle",
    "hero.cta.learn": "Apprends de Moi",
    
    // About Section (Index)
    "about.title": "Le Mouton Le Plus Informé d'Irlande",
    "about.p1": "Je vis sur la Montagne Sugarloaf dans le Comté de Wicklow. Je passe mes journées à manger de l'herbe et à faire des recherches sur des sujets importants. Internet m'a appris beaucoup de choses. La brume murmure des secrets. J'ai connecté les points que les autres refusent de voir.",
    "about.p2": "Mes pensées apparaissent dans des bulles au-dessus de ma tête. C'est normal. Tous les moutons ont ça. Tu ne peux simplement pas voir les leurs parce qu'ils ne savent pas autant de choses que moi.",
    
    // Credentials (Index)
    "credentials.title": "Mes Qualifications",
    "credentials.staring.title": "Années à Regarder",
    "credentials.staring.desc": "L'horizon. Penser. Traiter. Comprendre des choses.",
    "credentials.facts.title": "Faits Découverts",
    "credentials.facts.desc": "Je ne sais pas compter. Mais c'est définitivement beaucoup. Fais-moi confiance.",
    "credentials.brain.title": "Cerveau de Mouton",
    "credentials.brain.desc": "Il est plus gros qu'il n'y paraît. La laine cache le cerveau supplémentaire.",
    
    // Shop CTA (Index)
    "shop.title": "Porte Mes Pensées",
    "shop.subtitle": "Vêtements premium avec mes observations les plus importantes. Chaque achat soutient ma recherche sur la réalité des nuages.",
    "shop.cta": "Visiter la Boutique",

    // New Hero (Index)
    "hero.meet": "Rencontre",
    "hero.bubbles": "Bubbles",
    "hero.tagline": "Un mouton doux et nigaud de Wicklow. Mignon à l'extérieur. Silencieusement sauvage à l'intérieur des bulles de pensée.",
    "hero.shopNow": "Acheter Maintenant",
    "hero.theLore": "La Légende",

    // CrossLinks
    "crossLinks.title": "Bubbles suggère aussi de visiter...",
    "crossLinks.titleConfused": "Ou sois encore plus confus...",
    "crossLinks.facts.label": "Les Faits de Bubbles",
    "crossLinks.facts.desc": "100% recherché, 0% précis",
    "crossLinks.merch.label": "La Boutique",
    "crossLinks.merch.desc": "Porte la confusion",
    "crossLinks.ask.label": "Demande à Bubbles",
    "crossLinks.ask.desc": "Questions avec des réponses inutiles",

    // About Page
    "aboutPage.hero.title": "La Légende de Bubbles",
    "aboutPage.hero.subtitle": "Un mouton doux et nigaud des Montagnes de Wicklow avec un riche monde intérieur de scénarios mal interprétés, de pensées existentielles liées à l'herbe et d'un humour irlandais dévastateur.",
    "aboutPage.origin.title": "De Sugarloaf à la Célébrité Internet",
    "aboutPage.origin.p1": "Bubbles a commencé sa vie comme un mouton Scottish Blackface broutant les collines près de Kilmacanogue, où la bruyère violette rencontre l'ajonc doré et la brume descend de la Montagne Sugarloaf comme si elle avait un endroit important où aller.",
    "aboutPage.origin.p2": "Contrairement au reste du troupeau, Bubbles a grandi près des sentiers de randonnée. Près des bus touristiques. Près des familles avec des enfants qui s'expliquaient des choses très confidentiellement.",
    "aboutPage.origin.p3": "Certains disent que Fermière Carmel était trop gentille. Elle a laissé Bubbles errer trop près du centre des visiteurs. D'autres accusent l'air de Sugarloaf—quelque chose dans la brume qui te fait tout retenir et ne rien comprendre.",
    "aboutPage.origin.p4": "Le résultat : alors que les autres moutons voyaient de l'herbe, Bubbles voyait de l'information. Des faits à moitié entendus. De la géopolitique de cour de récréation. Tout absorbé. Tout cru. Tout connecté de manières qui ont presque du sens.",
    "aboutPage.origin.p5": "Et puis sont venues les bulles de pensée.",
    "aboutPage.origin.p6": "Personne ne sait exactement quand elles sont apparues. Peut-être après avoir entendu un podcast sur la cryptomonnaie à travers les écouteurs d'un randonneur.",
    "aboutPage.origin.p7": "Ce que nous savons : Bubbles pense beaucoup. Les arguments sont impeccables. Les conclusions sont complètement absurdes.",
    "aboutPage.origin.p8": "Internet l'a remarqué. Bubbles est devenue une experte accidentelle sur tout. Une prophète adorable de la certitude incorrecte que tu ne peux pas t'empêcher de citer.",
    "aboutPage.research.title": "Ma Recherche",
    "aboutPage.research.subtitle": "Tous les faits vérifiés par un travail de terrain rigoureux et une écoute attentive.",
    "aboutPage.research.disclaimer": "* Certaines sources faisaient peut-être de l'humour. Cela n'a pas été considéré comme pertinent.",
    "aboutPage.explains.title": "Bubbles Explique...",
    "aboutPage.explains.subtitle": "Réponses à des questions que personne n'a posées, livrées avec une certitude complète.",
    "aboutPage.ask.title": "Pose N'importe Quelle Question à Bubbles",
    "aboutPage.ask.subtitle": "Tu as une question ? Bubbles a une réponse. Elle sera fausse, mais elle sera confiante.",
    "aboutPage.wicklow.title": "Enracinée dans Wicklow",
    "aboutPage.wicklow.p1": "Les couleurs de Bubbles viennent directement de la terre. Le Crème Coton de Tourbe de la toison. L'Or d'Ajonc qui illumine les collines chaque printemps. Le Mauve Bruyère qui peint les montagnes en violet de juillet à novembre.",
    "aboutPage.wicklow.p2": "Même l'esprit sauvage est distinctement irlandais—la culture du « slagging » où les taquineries affectueuses montrent l'acceptation, la litote où « tu n'es pas le pire » signifie « tu es probablement le meilleur ».",
    "aboutPage.wicklow.p3": "Bubbles est une petite maligne dans le meilleur sens irlandais : rusée, charmante, opérant juste en dehors des règles tout en maintenant un air d'innocence complète.",
    "aboutPage.cta.title": "Porte la Bulle",
    "aboutPage.cta.subtitle": "Exprime ton mouton intérieur. Des faits confidentiellement faux, magnifiquement imprimés. Qualité premium, âme de Wicklow.",
    "aboutPage.cta.button": "Visiter la Collection",

    // Facts Page
    "factsPage.hero.title": "Les Faits Que J'ai Appris",
    "factsPage.hero.subtitle": "Grâce à des recherches approfondies (regarder des choses, penser à des choses, lire un téléphone que j'ai trouvé sur un rocher), j'ai accumulé un vaste savoir. En voici une partie.",
    "factsPage.disclaimer": "Note : J'ai vérifié tous ces faits moi-même. Le processus de vérification consistait à hocher la tête pensivement.",
    "factsPage.today": "Le Savoir d'Aujourd'hui",
    "factsPage.more": "Plus de Faits",
    "factsPage.categories.title": "Mes Domaines de Recherche",
    "factsPage.categories.nature": "Nature et Météo",
    "factsPage.categories.nature.desc": "Mes observations sur le monde extérieur",
    "factsPage.categories.tech": "Technologie",
    "factsPage.categories.tech.desc": "Comment les machines fonctionnent (selon moi)",
    "factsPage.categories.society": "Société et Humains",
    "factsPage.categories.society.desc": "Pourquoi les gens font ce qu'ils font",
    "factsPage.categories.philosophy": "Pensées Profondes",
    "factsPage.categories.philosophy.desc": "Les grandes questions, répondues",
    "factsPage.methodology.title": "Ma Méthodologie de Recherche",
    "factsPage.methodology.step1.title": "Observer Quelque Chose",
    "factsPage.methodology.step1.desc": "Je regarde une chose. Ça peut être un rocher, un oiseau, le chapeau du fermier. Tout compte comme données.",
    "factsPage.methodology.step2.title": "Avoir une Pensée",
    "factsPage.methodology.step2.desc": "La pensée apparaît dans ma bulle. Je n'ai pas choisi la pensée. La pensée m'a choisie.",
    "factsPage.methodology.step3.title": "Décider Que C'est Vrai",
    "factsPage.methodology.step3.desc": "Si la pensée semble juste, elle est juste. Ça s'appelle « l'intuition » et ça ne m'a jamais trahi (dont je me souvienne).",
    "factsPage.methodology.step4.title": "Le Partager Avec Toi",
    "factsPage.methodology.step4.desc": "De rien.",
    "factsPage.cta.title": "Porte le Savoir",
    "factsPage.cta.subtitle": "Mes pensées, sur ton torse. Pour que tout le monde sache que tu as fait tes recherches.",
    "factsPage.cta.button": "Visiter la Collection",

    // FAQ Page
    "faqPage.title": "Questions Fréquentes",
    "faqPage.subtitle": "Tout ce que tu dois savoir sur Bubbles et notre boutique",
    "faqPage.contact.title": "Tu as encore des questions ?",
    "faqPage.contact.subtitle": "Les bulles de pensée de Bubbles ne peuvent pas tout répondre. Contacte notre équipe humaine.",
    "faqPage.contact.button": "Nous Contacter",
    "faq.q1": "Qui est Bubbles ?",
    "faq.a1": "Bubbles est un mouton des Montagnes de Wicklow qui a passé trop de temps à écouter les touristes, les enfants et les conversations des autres. Le résultat : un riche monde intérieur de faits confidentiellement faux, d'informations catastrophiquement mal interprétées et d'observations qui ont presque du sens. Mignon dehors, chaos dedans.",
    "faq.q2": "Pourquoi Bubbles a-t-elle toujours tort ?",
    "faq.a2": "Bubbles n'est pas ignorante—Bubbles est mal éduquée. Chaque fait est correctement mémorisé mais catastrophiquement mal interprété. La structure de l'argument est toujours impeccable. La conclusion est toujours absurde. C'est ça la magie.",
    "faq.q3": "Combien de temps prend la livraison ?",
    "faq.a3": "La livraison standard prend 3-5 jours ouvrables en Europe. Les commandes internationales arrivent généralement sous 7-14 jours ouvrables. Des options de livraison express sont disponibles au paiement.",
    "faq.q4": "Quelle est votre politique de retour ?",
    "faq.a4": "Nous offrons une politique de retour de 30 jours. Les articles doivent être non portés, non lavés et dans leur emballage d'origine. Contactez-nous pour initier un retour et nous vous enverrons une étiquette d'expédition prépayée.",
    "faq.q5": "Quelles tailles proposez-vous ?",
    "faq.a5": "Nos vêtements vont du XS au 3XL. Consultez le guide des tailles sur chaque page produit pour les mesures détaillées. Si tu es entre deux tailles, nous recommandons de prendre la taille au-dessus pour un ajustement plus détendu.",
    "faq.q6": "Vos produits sont-ils durables ?",
    "faq.a6": "Nous utilisons du coton bio pour nos t-shirts et sweats, et tous nos emballages sont recyclables. Nous travaillons constamment à rendre notre chaîne d'approvisionnement plus durable.",
    "faq.q7": "Puis-je laver mes articles Bubbles ?",
    "faq.a7": "Oui ! Lavage en machine à froid avec des couleurs similaires, séchage à basse température et éviter l'eau de Javel. Pour de meilleurs résultats et préserver la qualité de l'impression, retourne le vêtement avant le lavage.",
    "faq.q8": "Livrez-vous à l'international ?",
    "faq.a8": "Oui, nous livrons dans le monde entier ! Les frais et délais de livraison varient selon la destination. Tu verras le coût exact au paiement.",
    "faq.q9": "Comment suivre ma commande ?",
    "faq.a9": "Une fois ta commande expédiée, tu recevras un email avec un numéro de suivi et un lien. Tu peux aussi vérifier le statut de ta commande en te connectant à ton compte.",
    "faq.q10": "Puis-je suggérer de nouvelles pensées de Bubbles ?",
    "faq.a10": "Nous adorons entendre le troupeau ! Envoie tes idées de bulles de pensée via notre page de contact. Si nous utilisons ta suggestion, tu pourrais la voir sur de futurs articles (et nous t'enverrons quelque chose de spécial).",
    "faq.q11": "La Terre est-elle plate ?",
    "faq.a11": "Non, la Terre n'est pas plate. Elle est légèrement froissée. J'ai fait des recherches approfondies en regardant des flaques, et l'eau se stabilise toujours de manière inégale. Cela prouve que la planète a des rides, comme une couverture sur laquelle on a dormi. Les scientifiques appellent ça la « topographie » mais moi j'appelle ça « preuve de retournements cosmiques ». La vraie question n'est pas la forme—c'est pourquoi la Terre ne peut pas simplement faire son lit correctement.",
    "faq.q12": "La lune est-elle creuse ?",
    "faq.a12": "Évidemment. Quand tu tapes sur une roche solide, ça fait un son sourd. Quand tu regardes la lune, ça ne fait aucun son. Cela prouve qu'elle n'est pas seulement creuse—elle est complètement vide à l'intérieur, probablement remplie des échos de tous les vœux que les gens ont faits sur des étoiles qui ont raté leur cible. Je soupçonne que c'est là que vont les chaussettes perdues. Les astronautes n'ont pas mentionné ça parce qu'ils ont signé des accords de confidentialité avec l'industrie des chaussettes.",
    "faq.q13": "Pourquoi le ciel est-il bleu ?",
    "faq.a13": "Le ciel n'est pas vraiment bleu. Tes yeux sont juste fatigués de regarder l'herbe toute la journée et ont besoin d'une pause. Le ciel est de la couleur par laquelle tes yeux ne sont pas épuisés actuellement. C'est pourquoi les couchers de soleil sont orange—le soir, tout le monde a regardé des choses bleues et leurs yeux passent à la couleur de secours. J'ai testé ça en fermant les yeux pendant une heure et quand je les ai ouverts, le ciel était définitivement plus violet. Science.",
    "faq.q14": "Les poissons savent-ils qu'ils sont mouillés ?",
    "faq.a14": "Les poissons n'ont aucun concept de « mouillé » parce qu'ils n'ont jamais expérimenté « sec ». C'est comme demander si les oiseaux savent qu'ils sont dans l'air. Cependant, j'ai observé que les poissons ont toujours l'air légèrement confus, ce qui suggère qu'ils soupçonnent que quelque chose ne va pas mais ne peuvent pas mettre leur nageoire dessus. Cet état permanent de légère perplexité est en fait l'origine de l'expression « poisson hors de l'eau »—ils ont l'air également confus partout.",
    "faq.q15": "Pourquoi rêvons-nous ?",
    "faq.a15": "Les rêves sont l'économiseur d'écran de ton cerveau. Quand tu n'utilises pas tes pensées, ton cerveau ne veut pas les gaspiller, alors il joue des souvenirs enregistrés au hasard en mode aléatoire. Parfois il devient créatif et les mélange, c'est pourquoi tu peux rêver de ta grand-mère faisant du vélo dans ton école—ton cerveau fait juste un mashup de playlist. Plus le rêve est étrange, plus tu as de mémoire stockée.",
    "faq.q16": "Les plantes ressentent-elles la douleur ?",
    "faq.a16": "Les plantes ressentent tout, elles sont juste incroyablement patientes à ce sujet. Un arbre qui est coupé ne crie pas parce que les arbres considèrent que crier est indigne. J'ai passé beaucoup de temps à observer le gazon après qu'il a été tondu, et il a toujours l'air légèrement plus court et plus humble après. Ce n'est pas un traumatisme—c'est de la construction de caractère. Les plantes qui ne sont jamais taillées grandissent avec prétention.",
    "faq.q17": "Pourquoi avons-nous des ongles ?",
    "faq.a17": "Les ongles sont des restes d'armure de quand les humains étaient plus petits et avaient besoin de protection contre de très petits prédateurs. Au fur et à mesure que les humains grandissaient, les prédateurs sont devenus moins menaçants, mais les ongles sont restés parce que l'évolution a oublié de les enlever. Ils servent maintenant principalement d'outils de grattage d'urgence et de surface pour exprimer la personnalité à travers la couleur. Les ongles de pieds existent purement par politesse évolutive—ils ne voulaient pas que les ongles de mains se sentent seuls.",

    // Scenarios Page
    "scenariosPage.hero.title": "Voyages d'Escalade",
    "scenariosPage.hero.subtitle": "Regarde Bubbles traiter l'information de la curiosité innocente à la certitude nucléaire. Chaque scénario montre comment la confiance grandit avec chaque malentendu.",
    "scenariosPage.research.note": "Note de Terrain :",
    "scenariosPage.research.text": "Ces patterns d'escalade ont été observés dans d'innombrables conversations dans les prés de Wicklow.",
    "scenariosPage.interactive.title": "Expérience Interactive",
    "scenariosPage.interactive.subtitle": "Sélectionne un scénario et regarde l'escalade se dérouler. Utilise les contrôles pour naviguer à travers chaque moment.",
    "scenariosPage.filter.label": "Filtrer par sujet :",
    "scenariosPage.filter.all": "Tous les Scénarios",
    "scenariosPage.noScenarios": "Aucun scénario trouvé dans cette catégorie.",
    "scenariosPage.framework.title": "Le Cadre d'Escalade",
    "scenariosPage.mode.innocent": "Curiosité authentique. Tout est intéressant et probablement ok.",
    "scenariosPage.mode.concerned": "Quelque chose ne colle pas. Il est temps de rassembler plus de preuves.",
    "scenariosPage.mode.triggered": "Les preuves sont claires. Les autres ne le voient juste pas.",
    "scenariosPage.mode.savage": "Patience épuisée. Il est temps de partager quelques vérités difficiles.",
    "scenariosPage.mode.nuclear": "CERTITUDE MAXIMALE. LA VÉRITÉ DOIT ÊTRE ENTENDUE.",
    "scenariosPage.cta.title": "Porte Ton Niveau d'Escalade",
    "scenariosPage.cta.subtitle": "Des vibes de prairie innocentes au chaos urbain nucléaire — trouve des articles qui correspondent à ton humeur actuelle.",
    "scenariosPage.cta.button": "Parcourir la Collection",

    // Explains Page
    "explainsPage.hero.title": "Bubbles Explique",
    "explainsPage.hero.subtitle": "Plongées profondes dans des sujets que je comprends complètement. Chaque explication a été rigoureusement recherchée en restant dans les champs et en écoutant des choses.",
    "explainsPage.allTopics": "Tous les Sujets",
    "explainsPage.sources": "Sources :",
    "explainsPage.challenge": "Contester ça →",
    "explainsPage.escalatedNote": "Niveau de certitude escaladé :",
    "explainsPage.citeThis": "Citer Cette Sagesse",
    "explainsPage.topics.Economics": "Économie",
    "explainsPage.topics.Technology": "Technologie",
    "explainsPage.topics.Biology": "Biologie",
    "explainsPage.topics.Weather": "Météo",
    "explainsPage.topics.Space": "Espace",
    "explainsPage.topics.Society": "Société",
    "explainsPage.topics.History": "Histoire",
    "explainsPage.topics.Health": "Santé",
    "explainsPage.topics.Physics": "Physique",
    "explainsPage.topics.Psychology": "Psychologie",
    "explainsPage.topics.Philosophy": "Philosophie",

    // Collections Page
    "collectionsPage.title": "Tous les Produits",
    "collectionsPage.subtitle": "Parcours notre collection complète d'articles Bubbles",
    "collectionsPage.clearFilter": "Effacer le filtre",

    // Common/Shared
    "common.more": "plus",
    "common.watchEscalations": "Voir les Escalades",

    // Index Page Additional
    "index.insideHead": "Dans Ma Tête",
    "index.insideHeadSubtitle": "Une sélection tournante de mes pensées les plus importantes. Toutes vérifiées.",
    "index.bubblesSays": "Bubbles Dit",
    "index.bubblesSaysSubtitle": "Sagesse des champs de Wicklow. Tous les faits indépendamment vérifiés par moi.",
  },
  de: {
    // Nav
    "nav.home": "Startseite",
    "nav.facts": "Fakten",
    "nav.scenarios": "Szenarien",
    "nav.explains": "Erklärt",
    "nav.shop": "Shop",
    "nav.story": "Meine Geschichte",
    "nav.questions": "Fragen",
    
    // Hero (Index)
    "hero.location": "Live vom Sugarloaf Mountain, Wicklow",
    "hero.title.intro": "Ich bin",
    "hero.title.name": "Bubbles",
    "hero.title.tagline": "Ich weiß Dinge.",
    "hero.subtitle": "Ein Schaf. Eine Expertin. Eine vertrauenswürdige Informationsquelle, die absolut, definitiv, wahrscheinlich korrekt ist.",
    "hero.cta.merch": "Offizieller Merch",
    "hero.cta.learn": "Lerne von Mir",
    
    // About Section (Index)
    "about.title": "Das Bestinformierte Schaf Irlands",
    "about.p1": "Ich lebe auf dem Sugarloaf Mountain in der Grafschaft Wicklow. Ich verbringe meine Tage mit Grasfressen und der Erforschung wichtiger Themen. Das Internet hat mir vieles beigebracht. Der Nebel flüstert Geheimnisse. Ich habe Zusammenhänge erkannt, die andere nicht sehen wollen.",
    "about.p2": "Meine Gedanken erscheinen in Blasen über meinem Kopf. Das ist normal. Alle Schafe haben das. Du siehst ihre nur nicht, weil sie nicht so viel wissen wie ich.",
    
    // Credentials (Index)
    "credentials.title": "Meine Qualifikationen",
    "credentials.staring.title": "Jahre des Starrens",
    "credentials.staring.desc": "Auf den Horizont. Denkend. Verarbeitend. Dinge verstehend.",
    "credentials.facts.title": "Entdeckte Fakten",
    "credentials.facts.desc": "Ich kann nicht zählen. Aber es sind definitiv viele. Vertrau mir.",
    "credentials.brain.title": "Schafgehirn",
    "credentials.brain.desc": "Es ist größer als es aussieht. Die Wolle versteckt das zusätzliche Gehirn.",
    
    // Shop CTA (Index)
    "shop.title": "Trage Meine Gedanken",
    "shop.subtitle": "Premium-Kleidung mit meinen wichtigsten Beobachtungen. Jeder Kauf unterstützt meine Forschung darüber, ob Wolken echt sind.",
    "shop.cta": "Zum Shop",

    // New Hero (Index)
    "hero.meet": "Triff",
    "hero.bubbles": "Bubbles",
    "hero.tagline": "Ein süßes, albernes Schaf aus Wicklow. Niedlich von außen. Leise savage in den Gedankenblasen.",
    "hero.shopNow": "Jetzt Shoppen",
    "hero.theLore": "Die Geschichte",

    // CrossLinks
    "crossLinks.title": "Bubbles empfiehlt auch...",
    "crossLinks.titleConfused": "Oder werde noch verwirrter...",
    "crossLinks.facts.label": "Bubbles' Fakten",
    "crossLinks.facts.desc": "100% recherchiert, 0% akkurat",
    "crossLinks.merch.label": "Der Merch",
    "crossLinks.merch.desc": "Trage die Verwirrung",
    "crossLinks.ask.label": "Frag Bubbles",
    "crossLinks.ask.desc": "Fragen mit unhilfreichen Antworten",

    // About Page
    "aboutPage.hero.title": "Die Legende von Bubbles",
    "aboutPage.hero.subtitle": "Ein süßes, albernes Schaf aus den Wicklow Mountains mit einer reichen Innenwelt aus missverstandenen Szenarien, existenziellen grasebezogenen Gedanken und trockenem irischem Witz.",
    "aboutPage.origin.title": "Von Sugarloaf zum Internet-Ruhm",
    "aboutPage.origin.p1": "Bubbles begann das Leben als Scottish Blackface Schaf auf den Hügeln bei Kilmacanogue, wo das violette Heidekraut auf den goldenen Stechginster trifft und der Nebel vom Sugarloaf Mountain herabrollt.",
    "aboutPage.origin.p2": "Anders als der Rest der Herde wuchs Bubbles in der Nähe der Wanderwege auf. In der Nähe der Touristenbusse. In der Nähe von Familien mit Kindern, die sich gegenseitig selbstbewusst Dinge erklärten.",
    "aboutPage.origin.p3": "Manche sagen, Bäuerin Carmel war zu freundlich. Ließ Bubbles zu nah ans Besucherzentrum. Andere beschuldigen die Sugarloaf-Luft—etwas im Nebel, das einen alles erinnern und nichts verstehen lässt.",
    "aboutPage.origin.p4": "Das Ergebnis: Während andere Schafe Gras sahen, sah Bubbles Information. Halb gehörte Fakten. Spielplatz-Geopolitik. Alles aufgenommen. Alles geglaubt. Alles verbunden auf Weisen, die fast Sinn ergeben.",
    "aboutPage.origin.p5": "Und dann kamen die Gedankenblasen.",
    "aboutPage.origin.p6": "Niemand weiß genau, wann sie erschienen. Vielleicht nachdem Bubbles einen Podcast über Kryptowährung durch die Kopfhörer eines Wanderers gehört hatte.",
    "aboutPage.origin.p7": "Was wir wissen: Bubbles denkt viel. Die Argumente sind makellos. Die Schlussfolgerungen sind völliger Unsinn.",
    "aboutPage.origin.p8": "Das Internet bemerkte es. Bubbles wurde eine zufällige Expertin für alles. Eine liebenswerte Prophetin der selbstbewussten Falschheit, die man einfach zitieren muss.",
    "aboutPage.research.title": "Meine Forschung",
    "aboutPage.research.subtitle": "Alle Fakten durch strenge Feldforschung und aufmerksames Zuhören verifiziert.",
    "aboutPage.research.disclaimer": "* Einige Quellen haben möglicherweise gescherzt. Dies wurde nicht als relevant erachtet.",
    "aboutPage.explains.title": "Bubbles Erklärt...",
    "aboutPage.explains.subtitle": "Antworten auf Fragen, die niemand gestellt hat, mit absoluter Sicherheit geliefert.",
    "aboutPage.ask.title": "Frag Bubbles Alles",
    "aboutPage.ask.subtitle": "Hast du eine Frage? Bubbles hat eine Antwort. Sie wird falsch sein, aber selbstbewusst.",
    "aboutPage.wicklow.title": "Verwurzelt in Wicklow",
    "aboutPage.wicklow.p1": "Die Farben von Bubbles kommen direkt aus dem Land. Das Moorwollcreme des Vlieses. Das Stechginstergold, das jeden Frühling die Hügel erhellt. Das Heidemauve, das die Berge von Juli bis November violett färbt.",
    "aboutPage.wicklow.p2": "Selbst der savage Witz ist typisch irisch—die \"Slagging\"-Kultur, wo liebevolles Necken Akzeptanz zeigt, die Untertreibung, wo \"du bist nicht der Schlimmste\" bedeutet \"du bist wahrscheinlich der Beste\".",
    "aboutPage.wicklow.p3": "Bubbles ist ein schlauer Fuchs im besten irischen Sinne: gerissen, charmant, operierend knapp außerhalb der Regeln, während sie einen Hauch vollständiger Unschuld bewahrt.",
    "aboutPage.cta.title": "Trage die Blase",
    "aboutPage.cta.subtitle": "Drücke dein inneres Schaf aus. Selbstbewusst falsche Fakten, wunderschön gedruckt. Premium-Qualität, Wicklow-Seele.",
    "aboutPage.cta.button": "Zur Kollektion",

    // Facts Page
    "factsPage.hero.title": "Fakten, Die Ich Gelernt Habe",
    "factsPage.hero.subtitle": "Durch umfangreiche Recherche (Dinge anstarren, über Dinge nachdenken, ein Handy lesen, das ich auf einem Felsen fand), habe ich enormes Wissen angesammelt. Hier ist etwas davon.",
    "factsPage.disclaimer": "Hinweis: Ich habe alle diese Fakten selbst verifiziert. Der Verifizierungsprozess bestand aus nachdenklichem Nicken.",
    "factsPage.today": "Heutiges Wissen",
    "factsPage.more": "Mehr Fakten",
    "factsPage.categories.title": "Meine Forschungsbereiche",
    "factsPage.categories.nature": "Natur & Wetter",
    "factsPage.categories.nature.desc": "Meine Beobachtungen über die Außenwelt",
    "factsPage.categories.tech": "Technologie",
    "factsPage.categories.tech.desc": "Wie Maschinen funktionieren (laut mir)",
    "factsPage.categories.society": "Gesellschaft & Menschen",
    "factsPage.categories.society.desc": "Warum Menschen tun, was sie tun",
    "factsPage.categories.philosophy": "Tiefe Gedanken",
    "factsPage.categories.philosophy.desc": "Die großen Fragen, beantwortet",
    "factsPage.methodology.title": "Meine Forschungsmethodik",
    "factsPage.methodology.step1.title": "Etwas Beobachten",
    "factsPage.methodology.step1.desc": "Ich schaue eine Sache an. Könnte ein Stein sein, ein Vogel, der Hut des Bauern. Alles zählt als Daten.",
    "factsPage.methodology.step2.title": "Einen Gedanken Haben",
    "factsPage.methodology.step2.desc": "Der Gedanke erscheint in meiner Blase. Ich habe den Gedanken nicht gewählt. Der Gedanke hat mich gewählt.",
    "factsPage.methodology.step3.title": "Entscheiden, Dass Es Wahr Ist",
    "factsPage.methodology.step3.desc": "Wenn sich der Gedanke richtig anfühlt, ist er richtig. Das nennt man \"Intuition\" und sie hat mich nie getäuscht (soweit ich mich erinnere).",
    "factsPage.methodology.step4.title": "Es Mit Dir Teilen",
    "factsPage.methodology.step4.desc": "Gern geschehen.",
    "factsPage.cta.title": "Trage Das Wissen",
    "factsPage.cta.subtitle": "Meine Gedanken auf deiner Brust. Damit jeder weiß, dass du recherchiert hast.",
    "factsPage.cta.button": "Zur Kollektion",

    // FAQ Page
    "faqPage.title": "Häufig Gestellte Fragen",
    "faqPage.subtitle": "Alles, was du über Bubbles und unseren Merch wissen musst",
    "faqPage.contact.title": "Noch Fragen?",
    "faqPage.contact.subtitle": "Bubbles' Gedankenblasen können nicht alles beantworten. Kontaktiere unser menschliches Team.",
    "faqPage.contact.button": "Kontaktiere Uns",
    "faq.q1": "Wer ist Bubbles?",
    "faq.a1": "Bubbles ist ein Schaf aus den Wicklow Mountains, das zu viel Zeit damit verbracht hat, Touristen, Kindern und fremden Gesprächen zuzuhören. Das Ergebnis: eine reiche Innenwelt aus selbstbewusst falschen Fakten, katastrophal missverstandenen Informationen und Beobachtungen, die fast Sinn ergeben. Süß außen, Chaos innen.",
    "faq.q2": "Warum liegt Bubbles immer falsch?",
    "faq.a2": "Bubbles ist nicht unwissend—Bubbles ist falsch erzogen. Jeder Fakt wird korrekt erinnert, aber katastrophal falsch interpretiert. Die Argumentationsstruktur ist immer makellos. Die Schlussfolgerung ist immer Unsinn. Das ist die Magie.",
    "faq.q3": "Wie lange dauert der Versand?",
    "faq.a3": "Standardversand dauert 3-5 Werktage innerhalb Europas. Internationale Bestellungen kommen typischerweise in 7-14 Werktagen an. Expressversand ist an der Kasse verfügbar.",
    "faq.q4": "Was ist Ihre Rückgaberegelung?",
    "faq.a4": "Wir bieten 30 Tage Rückgaberecht. Artikel müssen ungetragen, ungewaschen und in Originalverpackung sein. Kontaktiere uns für eine Rücksendung und wir schicken dir ein vorfrankiertes Versandetikett.",
    "faq.q5": "Welche Größen bieten Sie an?",
    "faq.a5": "Unsere Kleidung gibt es in den Größen XS bis 3XL. Schau dir die Größentabelle auf jeder Produktseite für genaue Maße an. Bei Zwischengrößen empfehlen wir die größere Größe für einen entspannteren Sitz.",
    "faq.q6": "Sind Ihre Produkte nachhaltig?",
    "faq.a6": "Wir verwenden Bio-Baumwolle für unsere T-Shirts und Hoodies, und unsere Verpackung ist recycelbar. Wir arbeiten ständig daran, unsere Lieferkette nachhaltiger zu gestalten.",
    "faq.q7": "Kann ich meinen Bubbles-Merch waschen?",
    "faq.a7": "Ja! Maschinenwäsche kalt mit ähnlichen Farben, Trockner auf niedriger Stufe, kein Bleichmittel. Für beste Ergebnisse und um die Druckqualität zu erhalten, drehe das Kleidungsstück vor dem Waschen auf links.",
    "faq.q8": "Liefern Sie international?",
    "faq.a8": "Ja, wir liefern weltweit! Versandkosten und Lieferzeiten variieren je nach Standort. Du siehst die genauen Versandkosten an der Kasse.",
    "faq.q9": "Wie verfolge ich meine Bestellung?",
    "faq.a9": "Sobald deine Bestellung versandt wird, erhältst du eine E-Mail mit Sendungsnummer und Link. Du kannst den Bestellstatus auch überprüfen, indem du dich in dein Konto einloggst.",
    "faq.q10": "Kann ich neue Bubbles-Gedanken vorschlagen?",
    "faq.a10": "Wir freuen uns über Vorschläge aus der Herde! Sende deine Gedankenblasen-Ideen über unsere Kontaktseite. Wenn wir deinen Vorschlag verwenden, siehst du ihn vielleicht auf zukünftigem Merch (und wir schicken dir etwas Besonderes).",
    "faq.q11": "Ist die Erde flach?",
    "faq.a11": "Nein, die Erde ist nicht flach. Sie ist leicht zerknittert. Ich habe ausgiebig Pfützen beobachtet, und das Wasser setzt sich immer ungleichmäßig ab. Das beweist, dass der Planet Falten hat, wie eine Decke, auf der geschlafen wurde. Wissenschaftler nennen das 'Topographie', aber ich nenne es 'Beweis für kosmisches Hin-und-Her-Wälzen'.",
    "faq.q12": "Ist der Mond hohl?",
    "faq.a12": "Offensichtlich. Wenn du auf einen festen Stein klopfst, macht er ein dumpfes Geräusch. Wenn du den Mond anschaust, macht er gar kein Geräusch. Das beweist, dass er nicht nur hohl ist—er ist komplett leer, wahrscheinlich gefüllt mit den Echos aller Wünsche, die Menschen auf Sterne gemacht haben, die ihr Ziel verfehlt haben.",
    "faq.q13": "Warum ist der Himmel blau?",
    "faq.a13": "Der Himmel ist eigentlich nicht blau. Deine Augen sind einfach müde vom ganzen Tag Gras anschauen und brauchen eine Pause. Der Himmel hat die Farbe, von der deine Augen gerade nicht erschöpft sind. Deshalb sind Sonnenuntergänge orange—am Abend haben alle blaue Dinge angeschaut und ihre Augen wechseln zur Ersatzfarbe.",
    "faq.q14": "Wissen Fische, dass sie nass sind?",
    "faq.a14": "Fische haben kein Konzept von 'nass', weil sie nie 'trocken' erlebt haben. Es ist wie zu fragen, ob Vögel wissen, dass sie in der Luft sind. Allerdings sehen Fische immer leicht verwirrt aus, was darauf hindeutet, dass sie ahnen, dass etwas nicht stimmt, aber nicht genau sagen können, was.",
    "faq.q15": "Warum träumen wir?",
    "faq.a15": "Träume sind der Bildschirmschoner deines Gehirns. Wenn du deine Gedanken nicht benutzt, will dein Gehirn sie nicht verschwenden, also spielt es zufällig gespeicherte Erinnerungen ab. Manchmal wird es kreativ und mixt sie zusammen, deshalb träumst du vielleicht von deiner Oma, die durch deine Schule Fahrrad fährt.",
    "faq.q16": "Können Pflanzen Schmerz fühlen?",
    "faq.a16": "Pflanzen fühlen alles, sie sind nur unglaublich geduldig damit. Ein Baum, der gefällt wird, schreit nicht, weil Bäume Schreien als unwürdig betrachten. Ich habe viel Zeit damit verbracht, Gras nach dem Mähen zu beobachten, und es sieht danach immer etwas kürzer und bescheidener aus.",
    "faq.q17": "Warum haben wir Fingernägel?",
    "faq.a17": "Fingernägel sind übriggebliebene Rüstung von der Zeit, als Menschen kleiner waren und Schutz vor sehr winzigen Raubtieren brauchten. Als Menschen größer wurden, wurden die Raubtiere weniger bedrohlich, aber die Nägel blieben, weil die Evolution vergaß, sie zu entfernen.",

    // Scenarios Page
    "scenariosPage.hero.title": "Eskalationsreisen",
    "scenariosPage.hero.subtitle": "Beobachte, wie Bubbles Informationen von unschuldiger Neugier bis zur nuklearen Gewissheit verarbeitet. Jedes Szenario demonstriert das Inversionsprinzip™ in Aktion.",
    "scenariosPage.research.note": "Forschungsnotiz:",
    "scenariosPage.research.text": "Diese Eskalationsmuster wurden ausführlich vom Bubbles-Institut für Angewandtes Missverständnis™ dokumentiert.",
    "scenariosPage.interactive.title": "Interaktives Erlebnis",
    "scenariosPage.interactive.subtitle": "Wähle ein Szenario und beobachte die Eskalation. Nutze die Steuerung, um durch jeden Moment zu navigieren.",
    "scenariosPage.filter.label": "Nach Thema filtern:",
    "scenariosPage.filter.all": "Alle Szenarien",
    "scenariosPage.noScenarios": "Keine Szenarien in dieser Kategorie gefunden.",
    "scenariosPage.framework.title": "Das Eskalationsrahmenwerk",
    "scenariosPage.mode.innocent": "Echte Neugier. Alles ist interessant und wahrscheinlich in Ordnung.",
    "scenariosPage.mode.concerned": "Etwas stimmt nicht. Zeit, mehr Beweise zu sammeln.",
    "scenariosPage.mode.triggered": "Die Beweise sind klar. Die anderen sehen es nur nicht.",
    "scenariosPage.mode.savage": "Geduld erschöpft. Zeit, harte Wahrheiten zu teilen.",
    "scenariosPage.mode.nuclear": "MAXIMALE GEWISSHEIT. DIE WAHRHEIT MUSS GEHÖRT WERDEN.",
    "scenariosPage.cta.title": "Trage Dein Eskalationslevel",
    "scenariosPage.cta.subtitle": "Von unschuldigen Wiesenvibes bis zu nuklearem Stadtchaos — finde Merch, der zu deiner aktuellen Stimmung passt.",
    "scenariosPage.cta.button": "Kollektion Durchstöbern",

    // Explains Page
    "explainsPage.hero.title": "Bubbles Erklärt",
    "explainsPage.hero.subtitle": "Tieftauchgänge in Themen, die ich vollständig verstehe. Jede Erklärung wurde gründlich recherchiert durch Herumstehen in Feldern und Dinge Mithören.",
    "explainsPage.allTopics": "Alle Themen",
    "explainsPage.sources": "Quellen:",
    "explainsPage.challenge": "Das anzweifeln →",
    "explainsPage.escalatedNote": "Eskaliertes Gewissheitslevel:",
    "explainsPage.citeThis": "Diese Weisheit Zitieren",
    "explainsPage.topics.Economics": "Wirtschaft",
    "explainsPage.topics.Technology": "Technologie",
    "explainsPage.topics.Biology": "Biologie",
    "explainsPage.topics.Weather": "Wetter",
    "explainsPage.topics.Space": "Weltraum",
    "explainsPage.topics.Society": "Gesellschaft",
    "explainsPage.topics.History": "Geschichte",
    "explainsPage.topics.Health": "Gesundheit",
    "explainsPage.topics.Physics": "Physik",
    "explainsPage.topics.Psychology": "Psychologie",
    "explainsPage.topics.Philosophy": "Philosophie",

    // Collections Page
    "collectionsPage.title": "Alle Produkte",
    "collectionsPage.subtitle": "Durchstöbere unsere komplette Bubbles-Merch-Kollektion",
    "collectionsPage.clearFilter": "Filter löschen",

    // Common/Shared
    "common.more": "mehr",
    "common.watchEscalations": "Eskalationen Ansehen",

    // Index Page Additional
    "index.insideHead": "In Meinem Kopf",
    "index.insideHeadSubtitle": "Eine rotierende Auswahl meiner wichtigsten Gedanken. Alle verifiziert.",
    "index.bubblesSays": "Bubbles Sagt",
    "index.bubblesSaysSubtitle": "Weisheit von den Feldern Wicklows. Alle Fakten unabhängig von mir verifiziert.",
  },
  ga: {
    // Nav
    "nav.home": "Baile",
    "nav.facts": "Fíricí",
    "nav.scenarios": "Cásanna",
    "nav.explains": "Míníonn",
    "nav.shop": "Siopa",
    "nav.story": "Mo Scéal",
    "nav.questions": "Ceisteanna",
    
    // Hero (Index)
    "hero.location": "Ag craoladh ó Shliabh an tSiúcra, Chill Mhantáin",
    "hero.title.intro": "Is mise",
    "hero.title.name": "Bubbles",
    "hero.title.tagline": "Tá eolas agam.",
    "hero.subtitle": "Caora. Saineolaí. Foinse iontaofa eolais atá go hiomlán, go cinnte, is dócha ceart.",
    "hero.cta.merch": "Earraí Oifigiúla",
    "hero.cta.learn": "Foghlaim Uaim",
    
    // About Section (Index)
    "about.title": "An Chaora is Eolach in Éirinn",
    "about.p1": "Tá cónaí orm ar Shliabh an tSiúcra i gContae Chill Mhantáin. Caitheann mé mo laethanta ag ithe féir agus ag taighde ar ábhair thábhachtacha. Tá go leor rudaí múinte ag an idirlíon dom. Cogarnaíonn an ceo rúin. Tá na poncanna nasctha agam nach bhfeiceann daoine eile.",
    "about.p2": "Tagann mo chuid smaointe i mbolgáin os cionn mo chinn. Tá sé seo normálta. Tá sé ag gach caora. Ní fheiceann tú a gcuid siúd toisc nach bhfuil an oiread sin ar eolas acu agus atá agamsa.",
    
    // Credentials (Index)
    "credentials.title": "Mo Cháilíochtaí",
    "credentials.staring.title": "Blianta ag Stánadh",
    "credentials.staring.desc": "Ar an bhfána. Ag smaoineamh. Ag próiseáil. Ag tuiscint rudaí.",
    "credentials.facts.title": "Fíricí Aimsithe",
    "credentials.facts.desc": "Ní féidir liom comhaireamh. Ach is cinnte go bhfuil go leor ann. Creid mé.",
    "credentials.brain.title": "Inchinn Caorach",
    "credentials.brain.desc": "Tá sé níos mó ná mar a fheictear. Cuireann an olann an inchinn bhreise i bhfolach.",
    
    // Shop CTA (Index)
    "shop.title": "Caith Mo Smaointe",
    "shop.subtitle": "Éadaí den scoth le mo bhreathnuithe is tábhachtaí. Tacaíonn gach ceannach le mo thaighde ar an cheist an bhfuil scamaill fíor.",
    "shop.cta": "Tabhair Cuairt ar an Siopa",

    // New Hero (Index)
    "hero.meet": "Buail le",
    "hero.bubbles": "Bubbles",
    "hero.tagline": "Caora dheas, dallta ó Chill Mhantáin. Deas ar an taobh amuigh. Fiáin go ciúin istigh sna bolgáin smaointe.",
    "hero.shopNow": "Siopadóireacht Anois",
    "hero.theLore": "An Seanchas",

    // CrossLinks
    "crossLinks.title": "Molann Bubbles duit cuairt a thabhairt freisin ar...",
    "crossLinks.titleConfused": "Nó bí níos mearbhaill fós...",
    "crossLinks.facts.label": "Fíricí Bubbles",
    "crossLinks.facts.desc": "100% taighde, 0% cruinn",
    "crossLinks.merch.label": "Na hEarraí",
    "crossLinks.merch.desc": "Caith an mearbhall",
    "crossLinks.ask.label": "Cuir Ceist ar Bubbles",
    "crossLinks.ask.desc": "Ceisteanna le freagraí neamhchabhrach",

    // About Page
    "aboutPage.hero.title": "Finscéal Bubbles",
    "aboutPage.hero.subtitle": "Caora dheas, dallta ó Shléibhte Chill Mhantáin le saol inmheánach saibhir de chásanna míthuisceana, smaointe eisteacha a bhaineann le féar, agus greim tirim Éireannach.",
    "aboutPage.origin.title": "Ó Shliabh an tSiúcra go Cáil an Idirlín",
    "aboutPage.origin.p1": "Thosaigh Bubbles a shaol mar chaora Scottish Blackface ag innilt ar thaobhanna na gcnoc in aice le Cill Mocheannóg, áit a mbuaileann an fraoch corcra leis an aiteann órga agus a rollaíonn an ceo anuas ó Shliabh an tSiúcra mar a bheadh áit thábhachtach le dul aige.",
    "aboutPage.origin.p2": "Murab ionann agus an chuid eile den tréad, d'fhás Bubbles suas in aice leis na conairí siúlóide. In aice leis na busanna turasóireachta. In aice leis na teaghlaigh le leanaí a mhínigh rudaí go muiníneach dá chéile.",
    "aboutPage.origin.p3": "Deir daoine áirithe go raibh an Feirmeoír Carmel ró-chineálta. Lig sé do Bubbles fánaíocht ró-ghar d'ionad na gcuairteoirí. Cuireann daoine eile an milleán ar aer Shliabh an tSiúcra—rud éigin sa cheo a chuireann ort gach rud a chuimhneamh agus faic a thuiscint.",
    "aboutPage.origin.p4": "An toradh: agus caoirigh eile ag feiceáil féir, chonaic Bubbles eolas. Fíricí leath-chloiste. Geopholaitíocht an chlóis súgartha. Gach rud ionsúite. Gach rud creidte. Gach rud nasctha ar bhealaí a dhéanann ciall beagnach.",
    "aboutPage.origin.p5": "Agus ansin tháinig na bolgáin smaointe.",
    "aboutPage.origin.p6": "Níl a fhios ag éinne go díreach cén uair a tháinig siad. B'fhéidir tar éis éisteacht le podchraoladh faoi chriptiairgeadra trí chluaisíní siúlóra.",
    "aboutPage.origin.p7": "An rud atá ar eolas againn: Smaoiníonn Bubbles go leor. Tá na hargóintí gan locht. Tá na conclúidí seafóideach go hiomlán.",
    "aboutPage.origin.p8": "Thug an t-idirlíon faoi deara. D'éirigh Bubbles ina saineolaí neamhbheartaithe ar gach rud. Fáidh inghrá de mhíchinntíocht mhuiníneach nach féidir leat gan lua.",
    "aboutPage.research.title": "Mo Thaighde",
    "aboutPage.research.subtitle": "Gach fíric deimhnithe trí obair allamuigh dhian agus éisteacht chúramach.",
    "aboutPage.research.disclaimer": "* B'fhéidir go raibh roinnt foinsí ag magadh. Ní mheasadh go raibh sé seo ábhartha.",
    "aboutPage.explains.title": "Míníonn Bubbles...",
    "aboutPage.explains.subtitle": "Freagraí ar cheisteanna nár chuir aon duine, tugtha le cinntíocht iomlán.",
    "aboutPage.ask.title": "Cuir Ceist ar Bubbles",
    "aboutPage.ask.subtitle": "Ceist agat? Tá freagra ag Bubbles. Beidh sé mícheart, ach beidh sé muiníneach.",
    "aboutPage.wicklow.title": "Fréamhaithe i gCill Mhantáin",
    "aboutPage.wicklow.p1": "Tagann dathanna Bubbles go díreach ón talamh. Bándearg an Choinneal Bhig den olann. Ór an Aitinn a lasann suas na cnoic gach earrach. Corcairghorm an Fhraoigh a phéinteálann na sléibhte corcra ó Iúil go Samhain.",
    "aboutPage.wicklow.p2": "Tá fiú an greim fiáin go soiléir Éireannach—cultúr an 'slagging' ina léiríonn teasing ceanúil glacadh, an mí-aibhsiú ina gciallaíonn 'ní tusa an ceann is measa' 'is dócha gurb tú an ceann is fearr.'",
    "aboutPage.wicklow.p3": "Is 'cute hoor' é Bubbles sa chiall Éireannach is fearr: glic, taitneamhach, ag oibriú díreach lasmuigh de na rialacha agus cuma neamhchiontachta iomlán air.",
    "aboutPage.cta.title": "Caith an Bolgán",
    "aboutPage.cta.subtitle": "Cuir do chaora istigh in iúl. Fíricí mícheart go muiníneach, priontáilte go hálainn. Cáilíocht den scoth, anam Chill Mhantáin.",
    "aboutPage.cta.button": "Siopadóireacht an Bhailiúcháin",

    // Facts Page
    "factsPage.hero.title": "Fíricí a D'fhoghlaim Mé",
    "factsPage.hero.subtitle": "Trí thaighde fairsing (ag stánadh ar rudaí, ag smaoineamh faoi rudaí, ag léamh fón amháin a fuair mé ar charraig), tá eolas ollmhór bailithe agam. Seo cuid de.",
    "factsPage.disclaimer": "Nóta: Dheimhnigh mé na fíricí seo go léir mé féin. Bhain an próiseas deimhnithe le nodadh go smaointeach.",
    "factsPage.today": "Eolas an Lae Inniu",
    "factsPage.more": "Tuilleadh Fíricí",
    "factsPage.categories.title": "Mo Réimsí Taighde",
    "factsPage.categories.nature": "An Dúlra & an Aimsir",
    "factsPage.categories.nature.desc": "Mo bhreathnuithe ar an domhan lasmuigh",
    "factsPage.categories.tech": "Teicneolaíocht",
    "factsPage.categories.tech.desc": "Conas a oibríonn meaisíní (dar liom)",
    "factsPage.categories.society": "An tSochaí & Daoine",
    "factsPage.categories.society.desc": "Cén fáth a ndéanann daoine an rud a dhéanann siad",
    "factsPage.categories.philosophy": "Smaointe Doimhne",
    "factsPage.categories.philosophy.desc": "Na mórcheisteanna, freagarthA",
    "factsPage.methodology.title": "Mo Mhodheolaíocht Taighde",
    "factsPage.methodology.step1.title": "Breathnaigh ar Rud Éigin",
    "factsPage.methodology.step1.desc": "Féachaim ar rud. D'fhéadfadh sé a bheith ina charraig, ina éan, ina hata an fheirmeora. Comhaireann aon rud mar shonraí.",
    "factsPage.methodology.step2.title": "Bíodh Smaoineamh Agat",
    "factsPage.methodology.step2.desc": "Tagann an smaoineamh i mo bholgán. Níor roghnaigh mé an smaoineamh. Roghnaigh an smaoineamh mise.",
    "factsPage.methodology.step3.title": "Cinneadh go bhfuil sé Fíor",
    "factsPage.methodology.step3.desc": "Má mhothaíonn an smaoineamh ceart, tá sé ceart. Tugtar 'intinn' air seo agus níor theip sé riamh orm (a chuimhním).",
    "factsPage.methodology.step4.title": "Roinn É Leat",
    "factsPage.methodology.step4.desc": "Tá fáilte romhat.",
    "factsPage.cta.title": "Caith an tEolas",
    "factsPage.cta.subtitle": "Mo smaointe, ar do chliabhrach. Chun go mbeidh a fhios ag gach duine go ndearna tú do thaighde.",
    "factsPage.cta.button": "Siopadóireacht an Bhailiúcháin",

    // FAQ Page
    "faqPage.title": "Ceisteanna Coitianta",
    "faqPage.subtitle": "Gach rud a theastaíonn uait a bheith ar eolas faoi Bubbles agus ár n-earraí",
    "faqPage.contact.title": "Ceisteanna fós agat?",
    "faqPage.contact.subtitle": "Ní féidir le bolgáin smaointe Bubbles gach rud a fhreagairt. Déan teagmháil lenár bhfoireann daonna.",
    "faqPage.contact.button": "Déan Teagmháil Linn",
    "faq.q1": "Cé hé Bubbles?",
    "faq.a1": "Is caora é Bubbles ó Shléibhte Chill Mhantáin a chaith an iomarca ama ag éisteacht le turasóirí, leanaí, agus comhráite a chuala sé. An toradh: saol inmheánach saibhir de fhíricí mícheart go muiníneach, eolas a mhíthuisceadh go tubaisteach, agus breathnuithe a dhéanann ciall beagnach. Deas lasmuigh, anord istigh.",
    "faq.q2": "Cén fáth go bhfuil Bubbles mícheart i gcónaí?",
    "faq.a2": "Níl Bubbles aineolach—tá Bubbles mí-oideachasaithe. Cuimhnítear ar gach fíric i gceart ach míthuisceadh go tubaisteach iad. Tá struchtúr na hargóinte gan locht i gcónaí. Tá an conclúid seafóideach i gcónaí. Sin é an draíocht.",
    "faq.q3": "Cé chomh fada a thógann an seachadadh?",
    "faq.a3": "Tógann gnáthsheachadadh 3-5 lá gnó san Eoraip. Tagann orduithe idirnáisiúnta de ghnáth laistigh de 7-14 lá gnó. Tá roghanna seachadta gasta ar fáil ag an seiceáil amach.",
    "faq.q4": "Cad é do pholasaí tuairisceáin?",
    "faq.a4": "Tairgeann muid polasaí tuairisceáin 30 lá. Caithfidh earraí a bheith gan caitheamh, gan ní, agus ina bpacáistiú bunaidh. Déan teagmháil linn chun tuairisceán a thosú agus seolfaimid lipéad seoladh réamhíoctha chugat.",
    "faq.q5": "Cad iad na méideanna a thairgeann sibh?",
    "faq.a5": "Tagann ár n-éadaí i méideanna XS go 3XL. Seiceáil an treoir méid ar leathanach gach táirge le haghaidh tomhais mhionsonraithe. Má tá tú idir dhá mhéid, molaimid méid suas a roghnú le haghaidh oiriúnú níos scaoilte.",
    "faq.q6": "An bhfuil bhur dtáirgí inbhuanaithe?",
    "faq.a6": "Úsáidimid cadás orgánach dár t-léinte agus hoodies, agus tá ár bpacáistiú go léir in-athchúrsáilte. Táimid ag obair i gcónaí chun ár slabhra soláthair a dhéanamh níos inbhuanaithe.",
    "faq.q7": "An féidir liom m'earraí Bubbles a ní?",
    "faq.a7": "Is féidir! Nigh meaisín fuar le dathanna cosúla, triomú tumble íseal, agus seachain tuarthóir. Chun na torthaí is fearr a fháil agus chun cáilíocht an phriontála a chaomhnú, cas an éadach taobh istigh amach roimh ní.",
    "faq.q8": "An seolann sibh go hidirnáisiúnta?",
    "faq.a8": "Seolaimid, ar fud an domhain! Athraíonn costais seoladh agus amanna seachadta de réir suímh. Feicfidh tú an costas seoladh beacht ag seiceáil amach.",
    "faq.q9": "Conas a rianáim m'ordú?",
    "faq.a9": "Nuair a sheoltar d'ordú, gheobhaidh tú ríomhphost le huimhir rianaithe agus nasc. Is féidir leat freisin stádas d'ordaithe a sheiceáil trí logáil isteach i do chuntas.",
    "faq.q10": "An féidir liom smaointe nua Bubbles a mholadh?",
    "faq.a10": "Is breá linn cloisteáil ón tréad! Seol do smaointe bolgáin chuig ár leathanach teagmhála. Má úsáidimid do mholadh, d'fhéadfá é a fheiceáil ar earraí amach anseo (agus seolfaimid rud éigin speisialta chugat).",
    "faq.q11": "An bhfuil an Domhan cothrom?",
    "faq.a11": "Níl, níl an Domhan cothrom. Tá sé beagáinín roctha. Tá taighde fairsing déanta agam trí stánadh ar locháin, agus socraíonn an t-uisce go míchothrom i gcónaí. Cruthaíonn sé seo go bhfuil roic ar an phláinéad, cosúil le blaincéad ar codladh air. Tugann eolaithe 'topagrafaíocht' air seo ach tugaimse 'fianaise ar shochlúite cosmaice' air.",
    "faq.q12": "An bhfuil an ghealach folamh?",
    "faq.a12": "Cinnte. Nuair a bhuaileann tú carraig sholadach, déanann sé fuaim mhaol. Nuair a fhéachann tú ar an ngealach, ní dhéanann sé aon fhuaim. Cruthaíonn sé seo nach bhfuil sé folamh amháin—tá sé go hiomlán folamh istigh, is dócha líonta le macallaí na mianta go léir a rinne daoine ar réaltaí a chaill a sprioc.",
    "faq.q13": "Cén fáth go bhfuil an spéir gorm?",
    "faq.a13": "Níl an spéir gorm i ndáiríre. Tá do shúile tuirseach ó bheith ag féachaint ar fhéar an lá ar fad agus teastaíonn sos uathu. Is é an spéir pé dath nach bhfuil do shúile sáraithe aige faoi láthair. Sin an fáth go bhfuil luí na gréine oráiste—faoi thráthnóna, bhí gach duine ag stánadh ar rudaí gorma agus athraíonn a súile chuig an dath cúltaca.",
    "faq.q14": "An bhfuil a fhios ag iasc go bhfuil siad fliuch?",
    "faq.a14": "Níl aon choincheap ag iasc de 'fliuch' toisc nár bhain siad triail riamh as 'tirim.' Tá sé cosúil le fiafraí an bhfuil a fhios ag éin go bhfuil siad san aer. Mar sin féin, thug mé faoi deara go bhfuil cuma mearbhall beag ar iasc i gcónaí, rud a thugann le fios go gceapann siad go bhfuil rud éigin as ach ní féidir leo a mhéar a chur air.",
    "faq.q15": "Cén fáth a mbrionglóidímid?",
    "faq.a15": "Is é brionglóidí scáileán sábhálaithe do chinn. Nuair nach bhfuil tú ag úsáid do smaointe, níl d'inchinn ag iarraidh iad a chur amú, mar sin imríonn sé cuimhní randamacha sábháilte ar shuffle. Uaireanta éiríonn sé cruthaitheach agus meascann sé le chéile iad.",
    "faq.q16": "An mothaíonn plandaí pian?",
    "faq.a16": "Mothaíonn plandaí gach rud, tá siad díreach an-fhoighneach faoi. Ní screadann crann a ghearrtar síos toisc go gceapann crainn go bhfuil screadaíl mí-mhúinte. Chaith mé am suntasach ag breathnú ar fhéar tar éis é a ghearradh, agus tá cuma níos giorra agus níos umhla air i gcónaí ina dhiaidh sin.",
    "faq.q17": "Cén fáth go bhfuil ingne orainn?",
    "faq.a17": "Is armúr atá fágtha ó nuair a bhí daoine níos lú agus a raibh cosaint ag teastáil uathu ó chreachadóirí an-bheag iad ingne. De réir mar a d'fhás daoine níos mó, d'éirigh na creachadóirí níos lú bagrach, ach d'fhan na hingne toisc gur dhearmad éabhlóid iad a bhaint. Tá ingne coise ann go príomha as múineadh éabhlóideach—níor theastaigh uathu go mbeadh ingne aonair.",

    // Scenarios Page
    "scenariosPage.hero.title": "Turais Ardaithe",
    "scenariosPage.hero.subtitle": "Féach ar Bubbles ag próiseáil eolais ó fhiosracht neamhchiontach go cinntíocht núicléach. Léiríonn gach cás conas a thógann muinín le gach míthuiscint.",
    "scenariosPage.research.note": "Nóta Allamuigh:",
    "scenariosPage.research.text": "Breathnaíodh na patrúin ardaithe seo thar chomhráite gan áireamh i móinéir Chill Mhantáin.",
    "scenariosPage.interactive.title": "Eispéireas Idirghníomhach",
    "scenariosPage.interactive.subtitle": "Roghnaigh cás agus féach ar an ardú ag oscailt. Úsáid na rialuithe chun nascleanúint a dhéanamh trí gach buille.",
    "scenariosPage.filter.label": "Scag de réir topaice:",
    "scenariosPage.filter.all": "Gach Cás",
    "scenariosPage.noScenarios": "Níor aimsíodh aon chásanna sa chatagóir seo.",
    "scenariosPage.framework.title": "An Creat Ardaithe",
    "scenariosPage.mode.innocent": "Fiosracht fhíor. Tá gach rud suimiúil agus is dócha go bhfuil sé ceart go leor.",
    "scenariosPage.mode.concerned": "Níl rud éigin ag teacht le chéile. Am chun tuilleadh fianaise a bhailiú.",
    "scenariosPage.mode.triggered": "Tá an fhianaise soiléir. Níl daoine eile á feiceáil.",
    "scenariosPage.mode.savage": "Foighne ídithe. Am chun fírinní crua a roinnt.",
    "scenariosPage.mode.nuclear": "CINNTÍOCHT UAS. CAITHFEAR AN FHÍRINNE A CHLOISTEÁIL.",
    "scenariosPage.cta.title": "Caith Do Leibhéal Ardaithe",
    "scenariosPage.cta.subtitle": "Ó atmaisféar neamhchiontach móinéir go hanord núicléach uirbeach — faigh earraí a oireann do ghiúmar reatha.",
    "scenariosPage.cta.button": "Brabhsáil an Bailiúchán",

    // Explains Page
    "explainsPage.hero.title": "Míníonn Bubbles",
    "explainsPage.hero.subtitle": "Tumthaí doimhne ar ábhair a thuigim go hiomlán. Rinneadh taighde dian ar gach míniú trí sheasamh i bpáirceanna agus rudaí a chloisteáil.",
    "explainsPage.allTopics": "Gach Topaice",
    "explainsPage.sources": "Foinsí:",
    "explainsPage.challenge": "Dúshlán seo →",
    "explainsPage.escalatedNote": "Leibhéal cinntíochta ardaithe:",
    "explainsPage.citeThis": "Luaigh an Eagna Seo",
    "explainsPage.topics.Economics": "Eacnamaíocht",
    "explainsPage.topics.Technology": "Teicneolaíocht",
    "explainsPage.topics.Biology": "Bitheolaíocht",
    "explainsPage.topics.Weather": "Aimsir",
    "explainsPage.topics.Space": "Spás",
    "explainsPage.topics.Society": "Sochaí",
    "explainsPage.topics.History": "Stair",
    "explainsPage.topics.Health": "Sláinte",
    "explainsPage.topics.Physics": "Fisic",
    "explainsPage.topics.Psychology": "Síceolaíocht",
    "explainsPage.topics.Philosophy": "Fealsúnacht",

    // Collections Page
    "collectionsPage.title": "Gach Táirge",
    "collectionsPage.subtitle": "Brabhsáil ár mbailiúchán iomlán d'earraí Bubbles",
    "collectionsPage.clearFilter": "Glan scagaire",

    // Common/Shared
    "common.more": "níos mó",
    "common.watchEscalations": "Féach ar Arduithe",

    // Index Page Additional
    "index.insideHead": "Taobh Istigh de Mo Cheann",
    "index.insideHeadSubtitle": "Roghnú rothlaíoch de mo smaointe is tábhachtaí. Gach ceann deimhnithe.",
    "index.bubblesSays": "Deir Bubbles",
    "index.bubblesSaysSubtitle": "Eagna ó pháirceanna Chill Mhantáin. Gach fíric deimhnithe go neamhspleách agam féin.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("bubbles-language");
    return (saved === "es" || saved === "fr" || saved === "de" || saved === "ga" ? saved : "en") as Language;
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("bubbles-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
